In [1]:
!pip install numpy

In [3]:
import numpy as np

In [4]:
#Array creation 

In [6]:
a = np.array(10)
type(a)

numpy.ndarray

In [7]:
#Zero dimensional array

In [8]:
z = np.array(10)
z.ndim

0

In [9]:
#One dimensional array 

In [12]:
o = np.array([10,12,12,15])
o.ndim

1

In [13]:
#two dinemsional array

In [15]:
t = np.array([[10,10,12,14,15]])
t.ndim

2

In [16]:
#Three dimensional array 

In [17]:
th = np.array([[[10,12,14,15,16]]])

In [18]:
th.ndim

3

In [19]:
#Change the data type of the array elements.

In [20]:
a = np.array([10,25,52,54])

In [21]:
a.dtype

dtype('int32')

In [22]:
a = np.array([10,15,52,54], dtype = 'float')
print(a.dtype)
print('Hello')
a

float64
Hello


array([10., 15., 52., 54.])

# Other way of creating of array

* 1. arange
* 2. linspace
* 3. zeros
* 4. ones
* 5. random

In [24]:
a = np.arange(1,21,2)
a

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [25]:
b = np.linspace(1,5,15, retstep=True)
b

(array([1.        , 1.28571429, 1.57142857, 1.85714286, 2.14285714,
        2.42857143, 2.71428571, 3.        , 3.28571429, 3.57142857,
        3.85714286, 4.14285714, 4.42857143, 4.71428571, 5.        ]),
 0.2857142857142857)

In [26]:
z = np.zeros([2,2])
z

array([[0., 0.],
       [0., 0.]])

In [27]:
o = np.ones([5,5])

In [28]:
o

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [29]:
r = np.random.rand(5,5)
r

array([[0.85818221, 0.6755685 , 0.75505732, 0.49002638, 0.29832694],
       [0.57249634, 0.31323703, 0.68053934, 0.74355423, 0.44982303],
       [0.99350316, 0.05157776, 0.55533456, 0.59889874, 0.79753062],
       [0.48870078, 0.83243866, 0.24817949, 0.71649917, 0.93159288],
       [0.37056087, 0.75006746, 0.22045639, 0.41719153, 0.7235751 ]])

In [30]:
r = np.random.randint(5, size = 10)
r

array([4, 3, 0, 2, 2, 2, 2, 2, 4, 0])

# Slicing and indexing of arrays

In [31]:
a = np.array([[1,2,3],[4,5,6]])

In [32]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [33]:
a[0,0]

1

In [34]:
a[1,2]

6

In [35]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [36]:
a[0,1:]

array([2, 3])

In [37]:
a[0:,1:]

array([[2, 3],
       [5, 6]])

In [38]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [39]:
#1 and 6
a[[0,1],[0,2]]

array([1, 6])

In [40]:
#3 and 4
a[[0,1],[2,0]]

array([3, 4])

# Reshaping the arrays

In [41]:
a = np.random.rand(5,2)

In [42]:
a

array([[0.82894845, 0.66099681],
       [0.55707116, 0.63962358],
       [0.83302893, 0.84043136],
       [0.87252951, 0.0629071 ],
       [0.50758061, 0.47387045]])

In [43]:
a.reshape(2,5)

array([[0.82894845, 0.66099681, 0.55707116, 0.63962358, 0.83302893],
       [0.84043136, 0.87252951, 0.0629071 , 0.50758061, 0.47387045]])

In [44]:
a.reshape(10,1)

array([[0.82894845],
       [0.66099681],
       [0.55707116],
       [0.63962358],
       [0.83302893],
       [0.84043136],
       [0.87252951],
       [0.0629071 ],
       [0.50758061],
       [0.47387045]])

In [45]:
a.reshape(1,10)

array([[0.82894845, 0.66099681, 0.55707116, 0.63962358, 0.83302893,
        0.84043136, 0.87252951, 0.0629071 , 0.50758061, 0.47387045]])

In [46]:
a.reshape(5,-1)

array([[0.82894845, 0.66099681],
       [0.55707116, 0.63962358],
       [0.83302893, 0.84043136],
       [0.87252951, 0.0629071 ],
       [0.50758061, 0.47387045]])

# Aggregate Functions

* The Python numpy aggregate functions are sum, max, mean ,average , product ,meadian , standard deviation , variance ,percentile and corrcoef. 

In [47]:
a.min()

0.06290709746547007

In [48]:
a.std()

0.23477213088604204

In [49]:
a.var()

0.05511795344077286

# Stacking 
 
* stacking is used to join 2 different arrays.
* vertical stacking.
* Horizontal stacking.

In [51]:
a = np.array([1,2,3,4,5])
b = np.array([4,5,6,8,7])

In [52]:
np.hstack([a,b])

array([1, 2, 3, 4, 5, 4, 5, 6, 8, 7])

In [53]:
np.vstack([a,b])

array([[1, 2, 3, 4, 5],
       [4, 5, 6, 8, 7]])